import imageone from "../image/img-1.jpg";
import imagetwo from "../image/img-2.jpg";

export const data = [
  {
    section: 1,
    text: "SILAHKAN BACA HURUF YANG ADA PADA GAMBAR YANG TELAH DISEDIAKAN. JIKA SISWA DAPAT MEMBACA SELURUH HURUF PADA GAMBAR MAKA KLIK ANGKA O JIKA SISWA TIDAK DAPAT MEMBACA HURUF PADA GAMBAR KLIK BERAPA HURUF YANG TIDAK DAPAT DI BACA SISWA. SERTA TULIS HURUF YANG TIDAK BISA DIBACA SISWA DI BAWAH GAMBAR YANG TELAH DISEDIAKAN. ",
    img: imageone,
  },
  {
    section: 2,
    text: "SILAHKAN BACA HURUF YANG ADA PADA GAMBAR YANG TELAH DISEDIAKAN. JIKA SISWA DAPAT MEMBACA SELURUH HURUF PADA GAMBAR MAKA KLIK ANGKA O JIKA SISWA TIDAK DAPAT MEMBACA HURUF PADA GAMBAR KLIK BERAPA HURUF YANG TIDAK DAPAT DI BACA SISWA. SERTA TULIS HURUF YANG TIDAK BISA DIBACA SISWA DI BAWAH GAMBAR YANG TELAH DISEDIAKAN. ",
    img: imagetwo,
  },
];
